
-- CREACION DE LA BASE DE DATOS;

DROP DATABASE IF EXISTS Huertica;
CREATE DATABASE Huertica;

-- CREACION DE LAS TABLAS;

CREATE TABLE ROL (
	ID_ROL 			INT AUTO_INCREMENT,
    NOMBRE_ROL 		VARCHAR(30),
    PRIMARY KEY(ID_ROL)
);

CREATE TABLE ESTADO (
	ID_ESTADO 		INT AUTO_INCREMENT,
    NOMBRE_ESTADO	VARCHAR(30),
    PRIMARY KEY(ID_ESTADO)
);

CREATE TABLE USUARIO (
	ID_USUARIO 			INT AUTO_INCREMENT,
    ID_ROL 				INT,
    ID_ESTADO 			INT,
    NOMBRE 				VARCHAR(50),
    APELLIDO_PATERNO 	VARCHAR(50),
    APELLIDO_MATERNO 	VARCHAR(50),
    CONTRASENA 			INT,
    CORREO 				VARCHAR(120),
    PRIMARY KEY (ID_USUARIO),
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY(ID_ROL) REFERENCES ROL(ID_ROL),
    CONSTRAINT FK_USUARIO_ESTADO FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
);

CREATE TABLE PROVINCIA(	
	ID_PROVINCIA 		INT auto_increment,
    NOMBRE_PROVINCIA 	VARCHAR(50),
    PRIMARY KEY(ID_PROVINCIA)
);

CREATE TABLE CANTON(
	ID_CANTON 			INT AUTO_INCREMENT,
	NOMBRE_CANTON 		VARCHAR(50),
    PRIMARY KEY(ID_CANTON)
);

CREATE TABLE DISTRITO(
	ID_DISTRITO 		INT AUTO_INCREMENT,
	NOMBRE_DISTRITO 	VARCHAR(50),
	PRIMARY KEY(ID_DISTRITO)
);

CREATE TABLE DIRECCION(
	ID_DIRECCION 		INT AUTO_INCREMENT,
    ID_PROVINCIA		INT,
    ID_CANTON			INT,
    ID_DISTRITO			INT,
    OTRAS_SENAS			VARCHAR(200),
    PRIMARY KEY PK_DIRECCION_DIRECCION (ID_DIRECCION, ID_PROVINCIA, ID_CANTON, ID_DISTRITO),
    CONSTRAINT FK_DIRECCION_PROVINCIA FOREIGN KEY(ID_PROVINCIA) REFERENCES PROVINCIA(ID_PROVINCIA),
    CONSTRAINT FK_DIRECCION_CANTON FOREIGN KEY (ID_CANTON) REFERENCES CANTON(ID_CANTON),
    CONSTRAINT FK_DIRECCION_DISTRITO FOREIGN KEY (ID_DISTRITO) REFERENCES DISTRITO(ID_DISTRITO)
);

CREATE TABLE INSTITUCION (
	ID_INSTITUCION 		INT AUTO_INCREMENT,
    ID_DIRECCION 		INT,
    NOMBRE				VARCHAR(100),
    PRIMARY KEY (ID_INSTITUCION),
    CONSTRAINT FK_INSTITUCION_DIRECCION FOREIGN KEY (ID_DIRECCIOON) REFERENCES DIRECCION(ID_DIRECCION)
);

CREATE TABLE TELEFONO (
	ID_INSTITUCION 		INT,
    TELEFONO 			VARCHAR(9),
    PRIMARY KEY(ID_INSTITUCION),
    CONSTRAINT FK_TELEFONO_INSTITUCION FOREIGN KEY (ID_INSTITUCION) REFERENCES TELEFONO(ID_INSTUTUCION)
);

CREATE TABLE HUERTA(
	ID_HUERTA 			INT AUTO_INCREMENT,
    ID_INSTITUCION 		INT,
    ID_ESTADO			INT,
    NOMBRE				VARCHAR(100),
    AREA_M2				INT,
    DESCRIPCION 		VARCHAR(200),
	PRIMARY KEY(ID_HUERTA),
    CONSTRAINT FK_HUERTA_INSTITUCION FOREIGN KEY (ID_INSTITUCION) REFERENCES INSTITUCION(ID_INSTITUCION),
    CONSTRAINT FK_HUERTA_ESTADO FOREIGN KEY (ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
);

CREATE TABLE REPORTE(
	ID_REPORTE		INT AUTO_INCREMENT,
	ID_HUERTA 		INT,
    FECHA 			DATE,
    PERIODO			VARCHAR(50),
    DESCRIPCION 	VARCHAR(500),
    PRIMARY KEY(ID_REPORTE),
    CONSTRAINT FK_REPORTE_HUERTA FOREIGN KEY(ID_HUERTA) REFERENCES HUERTA(ID_HUERTA)
);

CREATE TABLE GRUPO_ESTUDIANTIL(
	ID_GRUPO		 	   INT AUTO_INCREMENT,
    ID_DOCENTE_RESPONSABLE INT,
    NOMBRE					VARCHAR(30),
    GRADO					INT,
    SECCION					VARCHAR(5),
    ANYO 					VARCHAR(4),
    PRIMARY KEY(ID_GRUPO),
    CONSTRAINT FK_GRUPO_ESTUDIANTIL_DOCENTE FOREIGN KEY (ID_DOCENTE_RESPONSABLE) REFERENCES USUARIO(ID_USUARIO)
);

CREATE TABLE INTEGRANTES_GRUPOS(
	ID_USUARIO 		INT,
    ID_GRUPO		INT,
	CONSTRAINT FK_INTEGRANTES_GRUPOS_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
	CONSTRAINT FK_INTEGRANTES_GRUPOS_GRUPO FOREIGN KEY(ID_GRUPO) REFERENCES INTEGRANTES_GRUPOS(ID_GRUPO)
);

CREATE TABLE TIPO_CULTIVO(
	ID_TIPO_CULTIVO 	INT AUTO_INCREMENT,
    NOMBRE 				VARCHAR(30),
    NOMBRE_CIENTIFICO 	VARCHAR(50),
    TIEMPO_COSECHA 		INT,
    FRECUENCIA_RIEGO 	VARCHAR(30),
    FRECUENCIA_FERTILIZACION VARCHAR(30),
    OBSERVACIONES 		VARCHAR(200),
    PRIMARY KEY(ID_TIPO_CULTIVO)
);

CREATE TABLE CULTIVO(
	ID_CULTIVO			INT AUTO_INCREMENT,
    ID_HUERTA 			INT,
    ID_TIPO_CULTIVO		INT,
    ID_GRUPO		 	INT,
    ID_ESTADO			INT,
    FECHA_SIEMBRA		DATE,
    CANTIDAD			INT,
    PRIMARY KEY(ID_CULTIVO),
    CONSTRAINT FK_CULTIVO_HUERTA FOREIGN KEY(ID_HUERTA) REFERENCES HUERTA(ID_HUERTA),
    CONSTRAINT FK_CULTIVO_TIPO_CULTIVO FOREIGN KEY(ID_TIPO_CULTIVO) REFERENCES TIPO_CULTIVO(ID_TIPO_CULTIVO),
    CONSTRAINT FK_CULTIVO_GRUPO_ESTUDIANTIL FOREIGN KEY(ID_GRUPO) REFERENCES GRUPO_ESTUDIANTIL(ID_GRUPO),
    CONSTRAINT FK_CULTIVO_ESTADO FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
);

CREATE TABLE TIPO_ACTIVIDAD(
	ID_TIPO_ACTIVIDAD 		INT AUTO_INCREMENT,
    NOMBRE_ACTIVIDAD 			VARCHAR(50),
    PRIMARY KEY(ID_TIPO_ACTIVIDAD)
);

CREATE TABLE ACTIVIDAD(
	ID_ACTIVIDAD 		INT AUTO_INCREMENT,
    ID_CULTIVO			INT,
    ID_USUARIO			INT,
    ID_TIPO_ACTIVIDAD 	INT,
    FECHA_ACTIVIDAD 	DATE,
    DESCRIPCION 		VARCHAR(200),
    PRIMARY KEY(ID_ACTIVIDAD),
    CONSTRAINT FK_ACTIVIDAD_CULTIVO FOREIGN KEY(ID_CULTIVO) REFERENCES CULTIVO(ID_CULTIVO),
    CONSTRAINT FK_ACTIVIDAD_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_ACTIVIDAD_TIPO FOREIGN KEY(ID_TIPO_ACTIVIDAD) REFERENCES TIPO_ACTIVIDAD(ID_TIPO_ACTIVIDAD)
);

CREATE TABLE ALERTA(
	ID_ALERTA 			INT AUTO_INCREMENT,
    ID_CULTIVO			INT,
    ID_TIPO_ACTIVIDAD 	INT,
    ID_ESTADO 			INT,
    PRIMARY KEY(ID_ALERTA),
    CONSTRAINT FK_ALERTA_CULTIVO FOREIGN KEY(ID_CULTIVO) REFERENCES CULTIVO(ID_CULTIVO),
    CONSTRAINT FK_ALERTA_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_ALERTA_ESTADO FOREIGN KEY(ID_ESTADO) REFERENCES ESTADO(ID_ESTADO)
);







